version: '3.1'
services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      - MONGO_CONNECTION_STRING=mongodb+srv://atharva22110116:j1db3hmyyaWorY4l@fastapiproject.gfmoy1c.mongodb.net/
    volumes:
      - './data:/data/db'
